# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:

        delivery_address: virginie.allaghenkhaldi@gmail.com
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']
